---
apiVersion: v1
kind: ConfigMap
metadata:
  name: oidc-gangway-config
  namespace: kube-system
data:
  gangway.yaml: |
    clusterName: "skuba"

    redirectURL: "https://10.84.154.72:32001/callback"
    scopes: ["openid", "email", "groups", "profile", "offline_access"]

    serveTLS: true
    authorizeURL: "https://10.84.154.72:32000/auth"
    tokenURL: "https://10.84.154.72:32000/token"
    keyFile: /etc/gangway/pki/tls.key
    certFile: /etc/gangway/pki/tls.crt

    clientID: "oidc"
    clientSecret: "ca62f91e4b63bcf8de0edea0"
    usernameClaim: "email"
    apiServerURL: "https://10.84.154.72:6443"
    cluster_ca_path: "/var/run/secrets/kubernetes.io/serviceaccount/ca.crt"
    trustedCAPath: /etc/gangway/pki/ca.crt
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: oidc-gangway
  namespace: kube-system
  labels:
    app: oidc-gangway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oidc-gangway
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: oidc-gangway
    spec:
      serviceAccountName: oidc-gangway
      containers:
        - name: oidc-gangway
          image: registry.suse.de/devel/caasp/4.0/containers/containers/caasp/v4/gangway:3.1.0
          imagePullPolicy: IfNotPresent
          command: ["gangway", "-config", "/gangway/gangway.yaml"]
          env:
            - name: GANGWAY_SESSION_SECURITY_KEY
              valueFrom:
                secretKeyRef:
                  name: oidc-gangway-secret
                  key: session-key
          ports:
            - name: web
              containerPort: 8080
              protocol: TCP
          volumeMounts:
            - name: gangway-config-path
              mountPath: /gangway/
              readOnly: true
            - name: gangway-cert-path
              mountPath: /etc/gangway/pki
              readOnly: true
      volumes:
        - name: gangway-config-path
          configMap:
            name: oidc-gangway-config
            items:
              - key: gangway.yaml
                path: gangway.yaml
        - name: gangway-cert-path
          secret:
            secretName: oidc-gangway-cert
---
apiVersion: v1
kind: Service
metadata:
  name: oidc-gangway
  namespace: kube-system
spec:
  type: NodePort
  ports:
  - name: web
    port: 8080
    protocol: TCP
    targetPort: 8080
    nodePort: 32001
  selector:
    app: oidc-gangway
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: oidc-gangway
  namespace: kube-system
