name: Go
# This workflow is triggered on pushes and pull-requests to the repository
on: [push, pull_request]

jobs:

  build:
    # Job's name is Build
    name: Build
    # This job runs on Linux
    runs-on: ubuntu-latest
    steps:

      - name: Set up Go 1.12
        uses: actions/setup-go@v1
        with:
          go-version: 1.12
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v1

      - name: Get dependencies
        run: |
          go get -v -t -d ./...
          if [ -f Gopkg.toml ]; then
              curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
              dep ensure
          fi


      - name: Format
        run: go build -v .